//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientesRegistro.MODELS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cliente
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "El Nombre Comercial es Obligatorio")]
        public string Nombre_Comercial { get; set; }
        [Required(ErrorMessage = "El Nombre Contacto es Obligatorio")]
        public string Nombres { get; set; }
        [Required(ErrorMessage = "El Apellido Contacto es Obligatorio")]
        public string Apellidos { get; set; }
        [Required(ErrorMessage = "El Género Biológico es Obligatorio")]
        public string Sexo { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento { get; set; }
        [Required(ErrorMessage = "La Cedula es Obligatoria")]
        public string Cedula_RNC { get; set; }
        [Required(ErrorMessage = "La Direccion es Obligatoria")]
        public string Direccion { get; set; }
        [Required(ErrorMessage = "El Telefono es Obligatorio")]
        public string Telefono { get; set; }
        [EmailAddress(ErrorMessage = "El Email es Obligatorio")]
        public string Email { get; set; }
        public Nullable<int> TipoNCF { get; set; }
    
        public virtual TipoNCF TipoNCF1 { get; set; }
    }
}
